"""
ASTER - Exploratory Data Analysis
===================================
Produces the full EDA report: statistics, plots, and a saved summary CSV.

Usage:
    python eda.py
"""

import os, sys
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

from src.preprocessing.data_loader import preprocess
from src.features.feature_engineering import build_features

DATA_PATH   = os.path.join(ROOT, "data",   "bengaluru_traffic_events.csv")
ASSETS_PATH = os.path.join(ROOT, "assets")
os.makedirs(ASSETS_PATH, exist_ok=True)

BG   = "#0F1729"; CARD = "#1E2D4E"; TEXT = "#E2E8F0"; ACCENT = "#3B82F6"
TIER_COLORS = {"Low": "#22C55E", "Medium": "#F59E0B", "High": "#EF4444"}

plt.rcParams.update({
    "figure.facecolor": BG, "axes.facecolor": CARD,
    "text.color": TEXT, "axes.labelcolor": TEXT,
    "xtick.color": TEXT, "ytick.color": TEXT,
    "axes.edgecolor": "#2D4070", "grid.color": "#2D4070",
})


def load():
    df = preprocess(DATA_PATH)
    df = build_features(df)
    df["start_local"] = df["start_datetime"].dt.tz_convert("Asia/Kolkata")
    return df


def print_schema(df):
    print("\n" + "="*60)
    print("  DATASET OVERVIEW")
    print("="*60)
    print(f"  Shape              : {df.shape[0]:,} rows x {df.shape[1]} columns")
    print(f"  Date range         : {df['start_local'].min().date()} -> {df['start_local'].max().date()}")
    print(f"  Total events       : {len(df):,}")
    print(f"\n  Impact tier dist:")
    for t in ["Low","Medium","High"]:
        n = (df["impact_tier"] == t).sum()
        print(f"    {t:<10} {n:>5,}  ({n/len(df)*100:.1f}%)")
    print(f"\n  Event type:")
    for t, n in df["event_type"].value_counts().items():
        print(f"    {t:<15} {n:>5,}  ({n/len(df)*100:.1f}%)")
    miss = df.isnull().mean()
    miss = miss[miss > 0].sort_values(ascending=False)
    print(f"\n  Missing value columns ({len(miss)}):")
    for col, frac in miss.items():
        print(f"    {col:<35} {frac*100:.1f}%")


def print_operational_insights(df):
    print("\n" + "="*60)
    print("  OPERATIONAL INSIGHTS")
    print("="*60)

    print("\n  Top 10 event causes:")
    for cause, n in df["event_cause"].value_counts().head(10).items():
        print(f"    {cause:<30} {n:>5,}")

    print("\n  Top corridors (named only):")
    corr = df[df["corridor"] != "Non-corridor"]["corridor"].value_counts().head(8)
    for c, n in corr.items():
        print(f"    {c:<35} {n:>4,}")

    print("\n  Duration by vehicle type (median minutes):")
    veh_dur = df.groupby("veh_type")["duration_minutes"].median().sort_values(ascending=False)
    for vt, d in veh_dur.dropna().items():
        print(f"    {vt:<20} {d:.1f} min")

    dur = df["duration_minutes"].dropna()
    dur_pos = dur[dur > 0]
    print(f"\n  Resolution time stats (n={len(dur_pos):,}):")
    print(f"    Median      : {dur_pos.median():.1f} min")
    print(f"    Mean        : {dur_pos.mean():.1f} min")
    print(f"    p90         : {np.percentile(dur_pos, 90):.1f} min")
    print(f"    < 60 min    : {(dur_pos <= 60).sum():,} ({(dur_pos <= 60).mean()*100:.1f}%)")
    print(f"    1-3 hours   : {((dur_pos > 60) & (dur_pos <= 180)).sum():,}")
    print(f"    > 3 hours   : {(dur_pos > 180).sum():,}")

    peak = df[df["hour"].between(7, 10) | df["hour"].between(17, 21)]
    offpeak = df[~(df["hour"].between(7, 10) | df["hour"].between(17, 21))]
    high_peak = (peak["impact_tier"] == "High").mean()
    high_off  = (offpeak["impact_tier"] == "High").mean()
    print(f"\n  High-impact rate by time:")
    print(f"    Peak hours    : {high_peak*100:.1f}%  ({len(peak):,} events)")
    print(f"    Off-peak      : {high_off*100:.1f}%  ({len(offpeak):,} events)")


def save_summary_csv(df):
    summary_rows = []
    for cause in df["event_cause"].value_counts().head(15).index:
        sub = df[df["event_cause"] == cause]
        summary_rows.append({
            "event_cause": cause,
            "total_events": len(sub),
            "high_impact_pct": round((sub["impact_tier"] == "High").mean() * 100, 1),
            "medium_impact_pct": round((sub["impact_tier"] == "Medium").mean() * 100, 1),
            "road_closure_pct": round(sub["road_closure_flag"].mean() * 100, 1),
            "median_duration_min": round(sub["duration_minutes"].dropna().median(), 1),
        })
    summary = pd.DataFrame(summary_rows)
    out = os.path.join(ASSETS_PATH, "eda_cause_summary.csv")
    summary.to_csv(out, index=False)
    print(f"\n  Saved summary: {out}")


def plot_all(df):
    """Generate and save all EDA plots."""
    # Already generated by the pipeline; check and regenerate if missing
    plots_needed = {
        "eda_impact_dist.png":   _plot_impact_dist,
        "eda_cause_dist.png":    _plot_cause_dist,
        "eda_hourly.png":        _plot_hourly,
        "eda_corridors.png":     _plot_corridors,
        "eda_zones.png":         _plot_zones,
        "eda_monthly_trend.png": _plot_monthly,
        "eda_duration.png":      _plot_duration,
        "eda_heatmap.png":       _plot_heatmap,
    }
    for fname, fn in plots_needed.items():
        fpath = os.path.join(ASSETS_PATH, fname)
        if not os.path.exists(fpath):
            print(f"  Generating {fname}...")
            fn(df, fpath)
        else:
            print(f"  Already exists: {fname}")


def _plot_impact_dist(df, path):
    fig, ax = plt.subplots(figsize=(8, 5))
    tc = df["impact_tier"].value_counts()
    ax.bar(["Low", "Medium", "High"],
           [tc.get("Low",0), tc.get("Medium",0), tc.get("High",0)],
           color=[TIER_COLORS["Low"], TIER_COLORS["Medium"], TIER_COLORS["High"]],
           width=0.5, alpha=0.9)
    ax.set_title("Event Impact Distribution", fontsize=13, fontweight="bold", pad=12)
    ax.set_ylabel("Event Count")
    ax.grid(axis="y", alpha=0.3); ax.spines[["top","right"]].set_visible(False)
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


def _plot_cause_dist(df, path):
    fig, ax = plt.subplots(figsize=(10, 6))
    cd = df["event_cause"].value_counts().head(12)
    ax.barh([c.replace("_"," ").title() for c in cd.index[::-1]],
            cd.values[::-1], color=ACCENT, alpha=0.9)
    ax.set_title("Events by Root Cause", fontsize=13, fontweight="bold", pad=12)
    ax.grid(axis="x", alpha=0.3); ax.spines[["top","right"]].set_visible(False)
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


def _plot_hourly(df, path):
    fig, ax = plt.subplots(figsize=(12, 5))
    hourly = df["hour"].value_counts().sort_index()
    def hc(h):
        if 7 <= h <= 10: return "#F59E0B"
        elif 17 <= h <= 21: return "#EF4444"
        elif 0 <= h <= 5: return "#6366F1"
        return ACCENT
    ax.bar(hourly.index, hourly.values,
           color=[hc(h) for h in hourly.index], width=0.8, alpha=0.9)
    ax.set_title("Events by Hour of Day (IST)", fontsize=13, fontweight="bold", pad=12)
    ax.set_xticks(range(24)); ax.set_xticklabels([f"{h:02d}" for h in range(24)])
    ax.grid(axis="y", alpha=0.3); ax.spines[["top","right"]].set_visible(False)
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


def _plot_corridors(df, path):
    fig, ax = plt.subplots(figsize=(10, 7))
    cd = df[df["corridor"] != "Non-corridor"]["corridor"].value_counts().head(12)
    ax.barh(cd.index[::-1], cd.values[::-1], color=ACCENT, alpha=0.9)
    ax.set_title("Top Corridors by Incident Volume", fontsize=13, fontweight="bold", pad=12)
    ax.grid(axis="x", alpha=0.3); ax.spines[["top","right"]].set_visible(False)
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


def _plot_zones(df, path):
    fig, ax = plt.subplots(figsize=(8, 6))
    zd = df[df["zone"] != "Unknown"]["zone"].value_counts()
    ax.bar(range(len(zd)), zd.values, color=ACCENT, alpha=0.9)
    ax.set_xticks(range(len(zd))); ax.set_xticklabels(zd.index, rotation=45, ha="right")
    ax.set_title("Events per Zone", fontsize=13, fontweight="bold", pad=12)
    ax.grid(axis="y", alpha=0.3); ax.spines[["top","right"]].set_visible(False)
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


def _plot_monthly(df, path):
    fig, ax = plt.subplots(figsize=(11, 5))
    import warnings; warnings.filterwarnings("ignore")
    df["month_label"] = df["start_local"].dt.to_period("M").astype(str)
    monthly = df.groupby(["month_label","event_type"]).size().unstack(fill_value=0).sort_index()
    x = range(len(monthly))
    unp = monthly.get("unplanned", pd.Series(0, index=monthly.index)).values
    pln = monthly.get("planned",   pd.Series(0, index=monthly.index)).values
    ax.fill_between(x, unp, alpha=0.4, color=ACCENT)
    ax.plot(x, unp, color=ACCENT, lw=2, label="Unplanned")
    ax.fill_between(x, pln, alpha=0.6, color="#F59E0B")
    ax.plot(x, pln, color="#F59E0B", lw=2, label="Planned")
    ax.set_xticks(list(x)); ax.set_xticklabels(monthly.index, rotation=30, ha="right")
    ax.set_title("Monthly Event Volume", fontsize=13, fontweight="bold", pad=12)
    ax.legend(facecolor=CARD, edgecolor="none", labelcolor=TEXT)
    ax.grid(axis="y", alpha=0.3); ax.spines[["top","right"]].set_visible(False)
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


def _plot_duration(df, path):
    fig, ax = plt.subplots(figsize=(9, 5))
    dur = df["duration_minutes"].dropna()
    dur = dur[(dur > 0) & (dur <= 480)]
    ax.hist(dur, bins=40, color=ACCENT, alpha=0.8)
    ax.axvline(dur.median(), color="#F59E0B", lw=2, ls="--", label=f"Median: {dur.median():.0f} min")
    ax.set_title("Event Resolution Time Distribution", fontsize=13, fontweight="bold", pad=12)
    ax.legend(facecolor=CARD, edgecolor="none", labelcolor=TEXT)
    ax.grid(axis="y", alpha=0.3); ax.spines[["top","right"]].set_visible(False)
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


def _plot_heatmap(df, path):
    fig, ax = plt.subplots(figsize=(8, 7))
    pivot = pd.crosstab(df["event_cause"], df["impact_tier"]).reindex(
        columns=["Low","Medium","High"], fill_value=0)
    pivot = pivot.sort_values("High", ascending=False).head(12)
    sns.heatmap(pivot, ax=ax, cmap="YlOrRd", annot=True, fmt="d",
                linewidths=0.5, linecolor=BG, cbar_kws={"shrink": 0.8})
    ax.set_title("Event Cause x Impact Tier", fontsize=12, fontweight="bold", pad=12)
    ax.set_yticklabels([t.get_text().replace("_"," ").title() for t in ax.get_yticklabels()])
    plt.tight_layout(); plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG); plt.close()


if __name__ == "__main__":
    print("=" * 60)
    print("  ASTER - Exploratory Data Analysis")
    print("=" * 60)
    df = load()
    print_schema(df)
    print_operational_insights(df)
    save_summary_csv(df)
    print("\n  Generating / verifying plots...")
    plot_all(df)
    print("\n[OK] EDA complete. Outputs saved to:", ASSETS_PATH)
